DROP TABLE TUSER CASCADE CONSTRAINTS;
DROP TABLE GENDER CASCADE CONSTRAINTS;
DROP TABLE Subject CASCADE CONSTRAINTS;
DROP TABLE Blocked CASCADE CONSTRAINTS;
DROP TABLE Rating CASCADE CONSTRAINTS;
DROP TABLE Offer CASCADE CONSTRAINTS;
DROP TABLE Request CASCADE CONSTRAINTS;

DROP SEQUENCE seq_gender;
DROP SEQUENCE seq_subject;
DROP SEQUENCE seq_request;
DROP SEQUENCE seq_offer;